try: #-> se der erro, ele apenas vai pular, sem parar o programa